# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Typroducts
email: 
author:
  name: Typroducts
  about: homepage

description: >- # this means to ignore newlines until "baseurl:"
  Typroducts is a generic company website. It first started in 2012, this website is a basic website with a products page, an about me page, and a charity page. This website is hosted by Github, the founder of this website and company is Ming Lu. If you are seeking for more information, our company adress is at 2433 Belverny AVE, Toronto, ON. Below is our contact inforrmation if you would like to reach out.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


contacts:
  # - title: twitter 
  #   url: 'https://twitter.com/whyherro1'
  # - title: github
  #   url:  'https://github.com/iftw2/'
  # - title: facebook
  #   url: 'https://example.com/@jekyllrb'
  # - title: instagram
  #   url: 'https://example.com/@jekyllrb'
  # - title: linkedin
  #   url: 'https://example.com/@jekyllrb'
  # - title: youtube
  #   url: 'https://example.com/@jekyllrb'
  # - title: twitch
  #   url: 'https://example.com/@jekyllrb'
  # - title: telegram
  #   url: 'https://example.com/@jekyllrb'
  # - title: whatsapp
  #   url: 'https://example.com/@jekyllrb'
  # - title: discord
  #   url: 'https://example.com/@jekyllrb'
  # - title: slack
  #   url: 'https://example.com/@jekyllrb'
  - title: email
    url: mailto:ming.lu@student.tdsb.on.ca
  - title: twitter
    url: 'https://twitter.com/'
  - title: youtube
    url: 'https://youtube.com/'

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
